pipeline:
  build:
    image: maven:3-jdk-11
    commands:
      - mvn clean package

  gitea_release:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_api_key
      base_url: https://git.metaunix.net
      title: "${CI_COMMIT_TAG}"
      files:
        - target/Dragoon-*.jar
    when:
      event: tag
