pipeline:
  test:
    image: maven:3-eclipse-temurin-17
    commands:
      - microdnf install -y lsof
      - mvn test

  build:
    image: maven:3-eclipse-temurin-17
    commands:
      - mvn clean compile assembly:single

  package:
    image: maven:3-eclipse-temurin-17
    commands:
      - microdnf install -y rpm-build
      - mvn clean compile package -Dmaven.test.skip
    when:
      event: tag

  gitea_release:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_api_key
      base_url: https://git.metaunix.net
      title: "${CI_COMMIT_TAG}"
      files:
        - target/dragoon-*.jar
        - target/dragoon-*.deb
        - target/rpm/dragoon/RPMS/noarch/dragoon-*.rpm
    when:
      event: tag
