pipeline:
  test:
    image: maven:3-eclipse-temurin-17-alpine
    commands:
      - apk add lsof
      - mvn test

  build:
    image: maven:3-eclipse-temurin-17-alpine
    commands:
      - mvn clean compile assembly:single

  package:
    image: maven:3-eclipse-temurin-17-alpine
    commands:
      - apk add rpm
      - mvn clean compile package -Dmaven.test.skip
    when:
      event: tag

  gitea_release:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_api_key
      base_url: https://git.metaunix.net
      title: "${CI_COMMIT_TAG}"
      files:
        - target/dragoon-*.jar
        - target/dragoon-*.deb
        - target/rpm/dragoon/RPMS/noarch/dragoon-*.rpm
    when:
      event: tag

  copy_deb_package:
    image: appleboy/drone-scp
    settings:
      host: "repo.int.metaunix.net"
      username:
        from_secret: repo_admin
      password:
        from_secret: repo_password
      port: 22
      target: /srv/repo/apt/dragoon/
      source: target/dragoon-*.deb
      strip_components: 2
    when:
      event: tag

  copy_rpm_package:
    image: appleboy/drone-scp
    settings:
      host: "repo.int.metaunix.net"
      username:
        from_secret: repo_admin
      password:
        from_secret: repo_password
      port: 22
      target: /srv/repo/dnf/dragoon/
      source: target/rpm/dragoon/RPMS/noarch/dragoon-*.rpm
      strip_components: 2
    when:
      event: tag

  update_repos:
    image: appleboy/drone-ssh
    settings:
      host:
        - repo.int.metaunix.net
      username:
        from_secret: repo_admin
      password:
        from_secret: repo_password
      port: 22
      command_timeout: 2m
      script:
        - "sudo /home/xadmin/scripts/update_repo.sh"
    when:
      event: tag
